# fly.toml app configuration file generated for wedding-fe on 2023-07-02T14:17:02+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wedding-fe"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
